---
galaxy_info:
  role_name: caddy
  author: bhdicaire
  description: Install and configure Caddy reverse proxy in an LXC container
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - trixie

dependencies: []