---
- name: Restart Timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted

- name: Restart PVEProxy
  systemd:
    name: pveproxy
    state: restarted

- name: Reboot and wait
  reboot:
    reboot_timeout: 300
    msg: "Ansible: rebooting PVE"